# Module for locating Intel's Threading Building Blocks (APS).
#
# Customizable variables:
#   TBB_ROOT_DIR
#     Specifies APS's root directory.
#
# Read-only variables:
#   TBB_FOUND
#     Indicates whether the library has been found.
#
#   TBB_INCLUDE_DIRS
#      Specifies APS's include directory.
#
#   TBB_LIBRARIES
#     Specifies APS libraries that should be passed to target_link_libararies.
#

INCLUDE (FindPackageHandleStandardArgs)

FIND_PATH (PUPILTRACKER_ROOT_DIR
  NAMES include/pupiltracker/PupilTracker.h
  PATHS ENV PATH
  DOC "PUPILTRACKER root directory")

FIND_PATH (PUPILTRACKER_INCLUDE_DIR
  NAMES pupiltracker/PupilTracker.h
  HINTS ${PUPILTRACKER_ROOT_DIR}/include
  DOC "PUPILTRACKER include directory")

FIND_LIBRARY (PUPILTRACKER_LIBRARY_RELEASE
  NAMES pupiltracker
  HINTS ${PUPILTRACKER_ROOT_DIR}
  PATH_SUFFIXES lib
  DOC "PUPILTRACKER release library")

FIND_LIBRARY (PUPILTRACKER_LIBRARY_DEBUG
  NAMES pupiltrackerd
  HINTS ${PUPILTRACKER_ROOT_DIR}
  PATH_SUFFIXES lib
  DOC "PUPILTRACKER debug library")

IF (PUPILTRACKER_LIBRARY_RELEASE AND PUPILTRACKER_LIBRARY_DEBUG)
  SET (PUPILTRACKER_LIBRARY optimized ${PUPILTRACKER_LIBRARY_RELEASE} debug ${PUPILTRACKER_LIBRARY_DEBUG}
    CACHE DOC "PUPILTRACKER library")
ELSEIF (PUPILTRACKER_LIBRARY_RELEASE)
  SET (PUPILTRACKER_LIBRARY ${PUPILTRACKER_LIBRARY_RELEASE} CACHE DOC "PUPILTRACKER library")
ENDIF (PUPILTRACKER_LIBRARY_RELEASE AND PUPILTRACKER_LIBRARY_DEBUG)

SET (PUPILTRACKER_LIBRARIES ${PUPILTRACKER_LIBRARY})
SET (PUPILTRACKER_INCLUDE_DIRS ${PUPILTRACKER_INCLUDE_DIR})


MARK_AS_ADVANCED (PUPILTRACKER_INCLUDE_DIR PUPILTRACKER_LIBRARY PUPILTRACKER_LIBRARY_RELEASE
  PUPILTRACKER_LIBRARY_DEBUG)


FIND_PACKAGE_HANDLE_STANDARD_ARGS (PUPILTRACKER REQUIRED_VARS PUPILTRACKER_ROOT_DIR
  PUPILTRACKER_INCLUDE_DIR PUPILTRACKER_LIBRARY)
